### ISSUE TITLE
Plugin Not Working 

### ISSUE THREAD

**Issue by flowcreators** [JtdeGraaf/zen-remove-split-view-tab-highlight#2]
On Zen Browser Version 1.0.1-a.14 and the extension does basically nothing even after restarting the browser a few times. Maybe latest update broke it?

![Plugin bug](https://github.com/user-attachments/assets/0dbb4d6f-61dd-4096-bcec-95911346d339)

**Comment by JtdeGraaf** [comment]
Same issue here, I'll take a look this weekend.

Thanks for the report <3

**Comment by flowcreators** [comment]
Thanks!

> Same issue here, I'll take a look this weekend.
> 
> Thanks for the report <3

**Comment by Kiwinblue** [comment]
Just started using Zen, waiting on this as well 🙏🏼

**Comment by JtdeGraaf** [comment]
FYI: I fixed the issue and opened a PR to the theme store, fix should be available in your browser when https://github.com/zen-browser/theme-store/pull/712 is merged
